// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: Cluster_Display_v1.2.0

#include "../ui.h"

lv_obj_t *ui_screen_cluster = NULL;
lv_obj_t *ui_screen_image_rpm = NULL;
lv_obj_t *ui_mph_value_ = NULL;
lv_obj_t *ui_clock_value_ = NULL;
lv_obj_t *ui_background_panel_black = NULL;
lv_obj_t *ui_gear_value = NULL;
lv_obj_t *ui_signal_left_icon = NULL;
lv_obj_t *ui_signal_right_icon = NULL;
lv_obj_t *ui_mph_icon = NULL;
lv_obj_t *ui_arc_rpm = NULL;
lv_obj_t *ui_odometer_value = NULL;
lv_obj_t *ui_fuel_icon = NULL;
lv_obj_t *ui_bar_fuel = NULL;
lv_obj_t *ui_odometer_mi_char = NULL;
lv_obj_t *ui_bar_segement_overlay_ = NULL;
lv_obj_t *ui_temperature_icon = NULL;
lv_obj_t *ui_battery_icon = NULL;
lv_obj_t *ui_high_beam_icon = NULL;
lv_obj_t *ui_engine_icon_ = NULL;
lv_obj_t *ui_oil_icon_ = NULL;
lv_obj_t *ui_HESD_icon = NULL;
lv_obj_t *ui_temperature_value = NULL;

// event funtions
void ui_event_gear_value( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      gear_value_change( e );
}
}

void ui_event_arc_rpm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      rpm_arc_value_changed( e );
}
}

// build funtions

void ui_screen_cluster_screen_init(void)
{
ui_screen_cluster = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen_cluster, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_screen_image_rpm = lv_image_create(ui_screen_cluster);
lv_image_set_src(ui_screen_image_rpm, &ui_img_images_tach_17k_centered_25pct_png);
lv_obj_set_width( ui_screen_image_rpm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_screen_image_rpm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_screen_image_rpm, LV_ALIGN_TOP_RIGHT );
//lv_obj_add_flag( ui_screen_image_rpm, LV_OBJ_FLAG_CLICKABLE );   /// Flags
//lv_obj_remove_flag( ui_screen_image_rpm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_mph_value_ = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_mph_value_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mph_value_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mph_value_, 0 );
lv_obj_set_y( ui_mph_value_, -32 );
lv_obj_set_align( ui_mph_value_, LV_ALIGN_CENTER );
lv_label_set_text(ui_mph_value_,"000");
//lv_obj_remove_flag( ui_mph_value_, LV_OBJ_FLAG_PRESS_LOCK );    /// Flags
lv_obj_set_style_text_font(ui_mph_value_, &ui_font_LiberationSansBold170_, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_clock_value_ = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_clock_value_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock_value_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock_value_, -509 );
lv_obj_set_y( ui_clock_value_, 280 );
lv_obj_set_align( ui_clock_value_, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock_value_,"0:00");
//lv_obj_remove_flag( ui_clock_value_, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_align(ui_clock_value_, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_clock_value_, &ui_font_LiberstionSansBold_50_, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_background_panel_black = lv_obj_create(ui_screen_cluster);
lv_obj_set_width( ui_background_panel_black, 150);
lv_obj_set_height( ui_background_panel_black, 150);
lv_obj_set_x( ui_background_panel_black, -3 );
lv_obj_set_y( ui_background_panel_black, 142 );
lv_obj_set_align( ui_background_panel_black, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_background_panel_black, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_background_panel_black, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_background_panel_black, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_background_panel_black, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_background_panel_black, lv_color_hex(0x3C3C41), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_background_panel_black, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_background_panel_black, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_background_panel_black, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_background_panel_black, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_background_panel_black, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_background_panel_black, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gear_value = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_gear_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gear_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_gear_value, -4 );
lv_obj_set_y( ui_gear_value, 147 );
lv_obj_set_align( ui_gear_value, LV_ALIGN_CENTER );
lv_label_set_text(ui_gear_value,"N");
lv_obj_set_style_text_color(ui_gear_value, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_gear_value, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_gear_value, &ui_font_LiberationSansBold_120_Gear, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_signal_left_icon = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_signal_left_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_signal_left_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_signal_left_icon, -539 );
lv_obj_set_y( ui_signal_left_icon, -280 );
lv_obj_set_align( ui_signal_left_icon, LV_ALIGN_CENTER );
lv_label_set_text(ui_signal_left_icon,"");
lv_obj_set_style_text_color(ui_signal_left_icon, lv_color_hex(0x33FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_signal_left_icon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_signal_left_icon, &ui_font_fa_regular_icons_50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_signal_right_icon = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_signal_right_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_signal_right_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_signal_right_icon, 539 );
lv_obj_set_y( ui_signal_right_icon, -280 );
lv_obj_set_align( ui_signal_right_icon, LV_ALIGN_CENTER );
lv_label_set_text(ui_signal_right_icon,"");
lv_obj_set_style_text_color(ui_signal_right_icon, lv_color_hex(0x33FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_signal_right_icon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_signal_right_icon, &ui_font_fa_regular_icons_50, LV_PART_MAIN| LV_STATE_DEFAULT);

//@TODO: configure default or disable, along with checked for different color changes
lv_obj_set_style_text_color(ui_signal_right_icon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_signal_right_icon, 255, LV_PART_MAIN| LV_STATE_CHECKED);

lv_obj_set_style_text_color(ui_signal_right_icon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_text_opa(ui_signal_right_icon, 255, LV_PART_MAIN| LV_STATE_DISABLED);

ui_mph_icon = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_mph_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_mph_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_mph_icon, 0 );
lv_obj_set_y( ui_mph_icon, 42 );
lv_obj_set_align( ui_mph_icon, LV_ALIGN_CENTER );
lv_label_set_text(ui_mph_icon,"mph");
lv_obj_set_style_text_color(ui_mph_icon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_mph_icon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_mph_icon, &ui_font_LiberstionSansBold_32_MPH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_arc_rpm = lv_arc_create(ui_screen_cluster);
lv_obj_set_width( ui_arc_rpm, 1050);
lv_obj_set_height( ui_arc_rpm, 1050);
lv_obj_set_x( ui_arc_rpm, 1 );
lv_obj_set_y( ui_arc_rpm, 288 );
lv_obj_set_align( ui_arc_rpm, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_arc_rpm, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_arc_set_range(ui_arc_rpm, 0,17);
lv_arc_set_value(ui_arc_rpm, 17);
lv_arc_set_bg_angles(ui_arc_rpm,211,331);
lv_obj_set_style_radius(ui_arc_rpm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_arc_rpm, lv_color_hex(0xAABE31), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_arc_rpm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_outline_color(ui_arc_rpm, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_arc_rpm, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_color(ui_arc_rpm, lv_color_hex(0x398CDB), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_arc_rpm, 400, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_arc_rpm, 25, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_arc_rpm, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_arc_rpm, 0, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_arc_rpm, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_arc_rpm, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_odometer_value = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_odometer_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_odometer_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_odometer_value, 485 );
lv_obj_set_y( ui_odometer_value, 280 );
lv_obj_set_align( ui_odometer_value, LV_ALIGN_CENTER );
lv_label_set_text(ui_odometer_value,"00000 ");
lv_obj_set_style_text_font(ui_odometer_value, &ui_font_LiberstionSansBold_32_MPH, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fuel_icon = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_fuel_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fuel_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_fuel_icon, -544 );
lv_obj_set_y( ui_fuel_icon, 68 );
lv_obj_set_align( ui_fuel_icon, LV_ALIGN_CENTER );
lv_label_set_text(ui_fuel_icon,"	");
lv_obj_set_style_text_font(ui_fuel_icon, &ui_font_fa_regular_icons_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bar_fuel = lv_bar_create(ui_screen_cluster);
lv_bar_set_value(ui_bar_fuel,80,LV_ANIM_OFF);
lv_bar_set_start_value(ui_bar_fuel, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_bar_fuel, 15);
lv_obj_set_height( ui_bar_fuel, 300);
lv_obj_set_x( ui_bar_fuel, -583 );
lv_obj_set_y( ui_bar_fuel, 65 );
lv_obj_set_align( ui_bar_fuel, LV_ALIGN_CENTER );
//lv_obj_remove_flag( ui_bar_fuel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_radius(ui_bar_fuel, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bar_fuel, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bar_fuel, 100, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_bar_fuel, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_bar_fuel, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_bar_fuel, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_bar_fuel,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_bar_fuel, lv_obj_get_style_pad_right(ui_bar_fuel,LV_PART_MAIN) + 1, LV_PART_MAIN );

ui_odometer_mi_char = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_odometer_mi_char, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_odometer_mi_char, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_odometer_mi_char, 543 );
lv_obj_set_y( ui_odometer_mi_char, 280 );
lv_obj_set_align( ui_odometer_mi_char, LV_ALIGN_CENTER );
lv_label_set_text(ui_odometer_mi_char,"mi");
//lv_obj_remove_flag( ui_odometer_mi_char, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_font(ui_odometer_mi_char, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bar_segement_overlay_ = lv_image_create(ui_screen_cluster);
lv_image_set_src(ui_bar_segement_overlay_, &ui_img_images_bar_segment_overlay_bgmask_png);
lv_obj_set_width( ui_bar_segement_overlay_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_bar_segement_overlay_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_bar_segement_overlay_, -583 );
lv_obj_set_y( ui_bar_segement_overlay_, 64 );
lv_obj_set_align( ui_bar_segement_overlay_, LV_ALIGN_CENTER );
//lv_obj_remove_flag( ui_bar_segement_overlay_, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_temperature_icon = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_temperature_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temperature_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temperature_icon, 567 );
lv_obj_set_y( ui_temperature_icon, 195 );
lv_obj_set_align( ui_temperature_icon, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperature_icon,"");
//lv_obj_remove_flag( ui_temperature_icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_temperature_icon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temperature_icon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temperature_icon, &ui_font_fa_regular_icons_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_battery_icon = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_battery_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_battery_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_battery_icon, -200 );
lv_obj_set_y( ui_battery_icon, 280 );
lv_obj_set_align( ui_battery_icon, LV_ALIGN_CENTER );
lv_label_set_text(ui_battery_icon,"");

lv_obj_set_style_text_color(ui_battery_icon, lv_color_hex(0x890820), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_battery_icon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_battery_icon, &ui_font_fa_regular_icons_50, LV_PART_MAIN| LV_STATE_DEFAULT);
//@TODO: configure differnet states for color, (0x890820 BLUE)
lv_obj_set_style_text_color(ui_battery_icon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_text_opa(ui_battery_icon, 0, LV_PART_MAIN| LV_STATE_DISABLED);

ui_high_beam_icon = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_high_beam_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_high_beam_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_high_beam_icon, -100 );
lv_obj_set_y( ui_high_beam_icon, 280 );
lv_obj_set_align( ui_high_beam_icon, LV_ALIGN_CENTER );
lv_label_set_text(ui_high_beam_icon,"	");
//lv_obj_add_flag( ui_high_beam_icon, LV_OBJ_FLAG_CHECKABLE );   /// Flags
//lv_obj_remove_flag( ui_high_beam_icon, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE );    /// Flags
lv_obj_set_style_text_color(ui_high_beam_icon, lv_color_hex(0x1E20C9), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_high_beam_icon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_high_beam_icon, &ui_font_fa_regular_icons_50, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_high_beam_icon, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DISABLED );
lv_obj_set_style_text_opa(ui_high_beam_icon, 0, LV_PART_MAIN| LV_STATE_DISABLED);

ui_engine_icon_ = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_engine_icon_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_engine_icon_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_engine_icon_, 0 );
lv_obj_set_y( ui_engine_icon_, 277 );
lv_obj_set_align( ui_engine_icon_, LV_ALIGN_CENTER );
lv_label_set_text(ui_engine_icon_,"	");
//@TODO: configure differnet states for color
lv_obj_set_style_text_color(ui_engine_icon_, lv_color_hex(0xFFBF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_engine_icon_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_engine_icon_, &ui_font_fa_regular_icons_50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_engine_icon_, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(ui_engine_icon_, 0, LV_PART_MAIN| LV_STATE_CHECKED);

ui_oil_icon_ = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_oil_icon_, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_oil_icon_, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_oil_icon_, 100 );
lv_obj_set_y( ui_oil_icon_, 280 );
lv_obj_set_align( ui_oil_icon_, LV_ALIGN_CENTER );
lv_label_set_text(ui_oil_icon_,"");
lv_obj_set_style_text_color(ui_oil_icon_, lv_color_hex(0x890820), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_oil_icon_, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_oil_icon_, &ui_font_fa_regular_icons_50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HESD_icon = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_HESD_icon, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HESD_icon, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HESD_icon, 200 );
lv_obj_set_y( ui_HESD_icon, 280 );
lv_obj_set_align( ui_HESD_icon, LV_ALIGN_CENTER );
lv_label_set_text(ui_HESD_icon,"");
lv_obj_set_style_text_color(ui_HESD_icon, lv_color_hex(0x890820), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HESD_icon, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HESD_icon, &ui_font_fa_regular_icons_50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temperature_value = lv_label_create(ui_screen_cluster);
lv_obj_set_width( ui_temperature_value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temperature_value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temperature_value, 510 );
lv_obj_set_y( ui_temperature_value, 199 );
lv_obj_set_align( ui_temperature_value, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperature_value,"000");
lv_obj_set_style_text_font(ui_temperature_value, &ui_font_LiberstionSansBold_32_MPH, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_gear_value, ui_event_gear_value, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_arc_rpm, ui_event_arc_rpm, LV_EVENT_ALL, NULL);

}

void ui_screen_cluster_screen_destroy(void)
{
   if (ui_screen_cluster) lv_obj_del(ui_screen_cluster);

// NULL screen variables
ui_screen_cluster= NULL;
ui_screen_image_rpm= NULL;
ui_mph_value_= NULL;
ui_clock_value_= NULL;
ui_background_panel_black= NULL;
ui_gear_value= NULL;
ui_signal_left_icon= NULL;
ui_signal_right_icon= NULL;
ui_mph_icon= NULL;
ui_arc_rpm= NULL;
ui_odometer_value= NULL;
ui_fuel_icon= NULL;
ui_bar_fuel= NULL;
ui_odometer_mi_char= NULL;
ui_bar_segement_overlay_= NULL;
ui_temperature_icon= NULL;
ui_battery_icon= NULL;
ui_high_beam_icon= NULL;
ui_engine_icon_= NULL;
ui_oil_icon_= NULL;
ui_HESD_icon= NULL;
ui_temperature_value= NULL;

}
