// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiMeter

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_rpm_bg;
extern lv_obj_t *ui_rpm_arc;
extern lv_obj_t *ui_label_mph_value;
extern lv_obj_t *ui_label_mph;
extern lv_obj_t *ui_label_gear;
extern lv_obj_t *ui_label_gear_value;
extern lv_obj_t *ui_label_odometer_value;

// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

