// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: Cluster_Display_v1.2.0

#ifndef _CLUSTER_DISPLAY_V1_2_0_UI_H
#define _CLUSTER_DISPLAY_V1_2_0_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_screen_cluster.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_images_tach_17k_centered_25pct_png);   // assets/images/tach_17k_centered_25pct.png
LV_IMG_DECLARE( ui_img_images_bar_segment_overlay_bgmask_png);   // assets/images/bar_segment_overlay_bgmask.png

// FONTS
LV_FONT_DECLARE( ui_font_LiberationSansBold170_);
LV_FONT_DECLARE( ui_font_LiberationSansBold_120_Gear);
LV_FONT_DECLARE( ui_font_LiberstionSansBold_32_MPH);
LV_FONT_DECLARE( ui_font_LiberstionSansBold_50_);
LV_FONT_DECLARE( ui_font_fa_regular_icons_30);
LV_FONT_DECLARE( ui_font_fa_regular_icons_50);
LV_FONT_DECLARE( ui_font_fa_regular_icons_test_3);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
