// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 9.1.0
// Project name: Cluster_Display_v1.2.0

#ifndef UI_SCREEN_CLUSTER_H
#define UI_SCREEN_CLUSTER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_cluster
extern void ui_screen_cluster_screen_init(void);
extern void ui_screen_cluster_screen_destroy(void);
extern lv_obj_t *ui_screen_cluster;
extern lv_obj_t *ui_screen_image_rpm;
extern lv_obj_t *ui_mph_value_;
extern lv_obj_t *ui_clock_value_;
extern lv_obj_t *ui_background_panel_black;
extern void ui_event_gear_value( lv_event_t * e);
extern lv_obj_t *ui_gear_value;
extern lv_obj_t *ui_signal_left_icon;
extern lv_obj_t *ui_signal_right_icon;
extern lv_obj_t *ui_mph_icon;
extern void ui_event_arc_rpm( lv_event_t * e);
extern lv_obj_t *ui_arc_rpm;
extern lv_obj_t *ui_odometer_value;
extern lv_obj_t *ui_fuel_icon;
extern lv_obj_t *ui_bar_fuel;
extern lv_obj_t *ui_odometer_mi_char;
extern lv_obj_t *ui_bar_segement_overlay_;
extern lv_obj_t *ui_temperature_icon;
extern lv_obj_t *ui_battery_icon;
extern lv_obj_t *ui_high_beam_icon;
extern lv_obj_t *ui_engine_icon_;
extern lv_obj_t *ui_oil_icon_;
extern lv_obj_t *ui_HESD_icon;
extern lv_obj_t *ui_temperature_value;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

