// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: StiMeter

#ifndef _STIMETER_UI_H
#define _STIMETER_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * test_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1656279599); 
LV_IMG_DECLARE( ui_img_sti_logo_png); 

// FONTS
LV_FONT_DECLARE( ui_font_DotoLarge);
LV_FONT_DECLARE( ui_font_Doto_48);
LV_FONT_DECLARE( school_bell_48);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
